# Generated by Django 5.0.6 on 2025-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='quantity_sold',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='revenue',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='item_mrp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='item_name',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='item_visibility',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='item_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='outlet_location_type',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='outlet_size',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='outlet_type',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='sales_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
